version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: genai-backend
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - genai-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: genai-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - genai-network

  # Redis for caching (optional)
  redis:
    image: redis:alpine
    container_name: genai-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - genai-network

networks:
  genai-network:
    driver: bridge

volumes:
  redis_data: